Library.Web/Controllers/BookController.cs
using Library.Data.Infrastructure;
using Library.Data.Repositories;
using Library.Model.Models;
using Library.Service;
using Library.Web.Constants;
using Library.Web.HelperMethods;
using Library.Web.Models;
using Library.Web.Models.Book;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Drawing.Text;
using Windows.ApplicationModel.VoiceCommands;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Windows.UI.Xaml.Controls;


namespace Library.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IWebHostEnvironment _webhost;
        private readonly IStorageService _storageService;
        private readonly ICategoryService _categoryService;
        private readonly ILanguageService _languageService;
        private readonly IPublisherService _publisherService;
        private readonly IBookService _bookService;
        private readonly IAuthorService _authorService;
        private readonly IBookAuthorService _bookAuthorService;
        private readonly IBookPublisherService _bookPublisherService;
        private readonly IBookStorageService _bookStorageService;
		private readonly IBookCategoryService _bookCategoryService;
		private readonly ILogService _logService;
		List<AllBooksViewModel> allBooks = new List<AllBooksViewModel>();


		public BookController
        (
            IWebHostEnvironment webhost,
            ILogService logService,
            IStorageService storageService, 
            ICategoryService categoryService, 
            ILanguageService languageService, 
            IPublisherService publisherService, 
            IAuthorService authorService, 
            IBookService bookService,
			IBookAuthorService bookAuthorService,
			IBookPublisherService bookPublisherService,
			IBookStorageService bookStorageService,
			IBookCategoryService bookCategoryService
		)
        {
            _webhost = webhost;
            _logService = logService;
            _storageService = storageService;
            _categoryService = categoryService;
            _languageService = languageService;
            _publisherService = publisherService;
            _authorService = authorService;
            _bookService = bookService;
            _bookAuthorService = bookAuthorService;
            _bookPublisherService = bookPublisherService;
            _bookStorageService = bookStorageService;
            _bookCategoryService = bookCategoryService;
        }

        private async Task<List<Author>> GetAuthors(int id)
        {
			var books = await _bookService.GetAllBooksAsync();
			var authors = await _authorService.GetAllAuthorsAsync();
			var bookAuthors = await _bookAuthorService.GetAllBookAuthorsAsync();

			List<Author> _authors = (from b in books
						 join ba in bookAuthors
						 on b.Id equals ba.BookId
						 join a in authors
						 on ba.AuthorId equals a.Id
						 where ba.BookId == id
						 select a).ToList();
            
            return _authors;
		}

		private async Task<List<Publisher>> GetPublishers(int id)
		{
			var books = await _bookService.GetAllBooksAsync();
			var bookPublishers = await _bookPublisherService.GetAllBookPublishersAsync();
			var publishers = await _publisherService.GetAllPublishersAsync();

			List<Publisher> _publishers = (from b in books
									 join bp in bookPublishers
									 on b.Id equals bp.BookId
									 join p in publishers
									 on bp.PublisherId equals p.ID
									 where bp.BookId == id
									 select p).ToList();

			return _publishers;
		}

		private async Task<List<Category>> GetGenres(int id)
		{
			var books = await _bookService.GetAllBooksAsync();
			var bookGenres = await _bookCategoryService.GetAllBookCategoriesAsync();
			var genres = await _categoryService.GetAllCategoriesAsync();

			List<Category> _genres = (from b in books
										   join bg in bookGenres
										   on b.Id equals bg.BookId
										   join g in genres
										   on bg.CategoryId equals g.Id
										   where bg.BookId == id
										   select g).ToList();

			return _genres;
		}

		private async Task<List<Storage>> GetShelves(int id)
		{
			var books = await _bookService.GetAllBooksAsync();
			var bookShelves = await _bookStorageService.GetAllBookStoragesAsync();
			var shelves = await _storageService.GetAllStoragesAsync();

			List<Storage> _shelves = (from b in books
									  join bs in bookShelves
									  on b.Id equals bs.BookId
									  join s in shelves
									  on bs.StorageId equals s.Id
									  where bs.BookId == id
									  select s).ToList();

			return _shelves;
		}

		[HttpGet]
        public async Task<IActionResult> Index()
        {
            var books = await _bookService.GetAllBooksAsync();               

            //List<AllBooksViewModel> allBooks = new List<AllBooksViewModel>();

            foreach (var book in books)
            {
                AllBooksViewModel model = new AllBooksViewModel();

                model.Id = book.Id;
                model.Title = book.Title;
                model.Description = book.Description;
                model.Authors = await GetAuthors(book.Id);
				model.Publishers = await GetPublishers(book.Id);
                model.Genres = await GetGenres(book.Id);
                model.Shelves = await GetShelves(book.Id);				

				allBooks.Add(model);
            }

            return View(allBooks);
        }

        [HttpPost]
        public async Task<IActionResult> Index(AllBooksViewModel books)
        {
            await Index();
            return View();
        }

		public async Task<ActionResult> Delete(int id)
		{
			var book = await _bookService.GetBookByIdAsync(id);

            return View(book);
		}

        [HttpPost]
        public async Task<ActionResult> Delete(AllBooksViewModel model)
        {
            var book = await _bookService.GetBookByIdAsync(model.Id);
			await _bookAuthorService.DeleteManyBookAuthorsAsync(x => x.BookId == book.Id);
			await _bookPublisherService.DeleteManyBookPublishersAsync(x => x.BookId == book.Id);
			await _bookCategoryService.DeleteManyBookCategoriesAsync(x => x.BookId == book.Id);
			await _bookStorageService.DeleteManyBookStoragesAsync(x => x.BookId == book.Id);

			var imgToDelete = Path.Combine(_webhost.WebRootPath, "CoverPhotos", book.ImageLink);
			var removeImg = new FileStream(imgToDelete, FileMode.Open);

			//using (removeImg)
			//{
			//	await imgFile.CopyToAsync(imgToDelete);
			//}

			await _bookService.DeleteBookAsync(book);
			await Index();

			return RedirectToAction("Index");
		}

        private async Task<IActionResult> FillDropDownLists(CreateBookViewModel model)
        {
            var authors = await _authorService.GetAllAuthorsAsync();
            var publishers = await _publisherService.GetAllPublishersAsync();
            var languages = await _languageService.GetAllLanguagesAsync();
            var genres = await _categoryService.GetAllCategoriesAsync();
            var shelves = await _storageService.GetAllStoragesAsync();

            var _authors = authors.ToList();
            var _publishers = publishers.ToList();
            var _languages = languages.ToList();
            var _genres = genres.ToList();
            var _shelves = shelves.ToList();

            // title
            ViewBag.Title = model.Title; 
            
            // description
            ViewBag.Description = model.Description;             

            // authors
            List<SelectListItem> autorsLst = new List<SelectListItem>();

            foreach (var author in _authors)
            {
                autorsLst.Add(new SelectListItem() { Value = author.Id.ToString(), Text = String.Concat(author.FirstName, " ", author.LastName) });
            }

            ViewBag.Authors = autorsLst;

            // publishers
            List<SelectListItem> publishersLst = new List<SelectListItem>();

            foreach (var publisher in _publishers)
            {
                publishersLst.Add(new SelectListItem() { Value = publisher.ID.ToString(), Text = publisher.PublisherName });
            }

            ViewBag.Publishers = publishersLst;

            // languages
            List<SelectListItem> languagesLst = new List<SelectListItem>();

            foreach (var language in _languages)
            {
                languagesLst.Add(new SelectListItem() { Value = language.Id.ToString(), Text = language.LanguageName });
            }

            ViewBag.Languages = languagesLst;

            // genres
            List<SelectListItem> genresLst = new List<SelectListItem>();

            foreach (var genre in _genres)
            {
                genresLst.Add(new SelectListItem() { Value = genre.Id.ToString(), Text = genre.CategoryName });
            }

            ViewBag.Genres = genresLst;

            // shelves
            List<SelectListItem> shelvesLst = new List<SelectListItem>();

            foreach (var shelf in _shelves)
            {
                shelvesLst.Add(new SelectListItem() { Value = shelf.Id.ToString(), Text = String.Concat("shelf:", shelf.ShelfNumber.ToString(), "-", "closet:", shelf.ClosetNumber.ToString()) });
            }
            
            ViewBag.Shelves = shelvesLst;

            return View();
        }

        public async Task<IActionResult> Add()
        {
            CreateBookViewModel model = new CreateBookViewModel();
            await FillDropDownLists(model);
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateBookViewModel model, IFormFile imgFile)
        {
            await FillDropDownLists(model);

            if (ModelState.IsValid)
            {
                // save images to Folder "~/cover"
                var saveimg = Path.Combine(_webhost.WebRootPath, "photos\\cover", imgFile.FileName);

Library.Web/Controllers/EmailController.cs
using Library.Model.Models;
using Library.Service;
using Library.Web.Constants;
using Library.Web.Models;
using Library.Web.Models.Account;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Host;
using Windows.Graphics.Printing.PrintSupport;

namespace Library.Web.Controllers
{
    public class EmailController : Controller
    {
        private readonly IEmailService emailService;
        private readonly ILogService logService;       

        public EmailController(IEmailService emailService, ILogService logService)
        {
            this.emailService = emailService;
            this.logService = logService;
        }

        public async Task<ActionResult> Index()
        {
            var result = await emailService.GetAllEmailsAsync();
            return View(result);
        }

        public IActionResult Add() => View();

        // POST/language/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(EmailTemplateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = model.Adapt<Email>();
                await HelperMethods.LogHelper.AddEntityWithLog(entity, emailService.AddEmailAsync, logService);
                TempData["Success"] = Warnings.SuccessfullyAddedGeneric<Email>();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET /email/edit/3
        public async Task<ActionResult> Edit(int id)
        {
            var item = await emailService.GetEmailByIdAsync(id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST /email/edit/4
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EmailTemplateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = model.Adapt<Email>();
                await HelperMethods.LogHelper.UpdateEntityWithLog(entity, emailService.UpdateEmailAsync, logService);
                TempData["Success"] = Warnings.SuccessfullyAddedGeneric<Email>();

                return RedirectToAction("Index");
            }

            return View(model);
        }

        //GET /email/edit/3
        public async Task<ActionResult> Delete(int id)
        {
            var entity = await emailService.GetEmailByIdAsync(id);

            if (entity == null)
            {
                return NotFound();
            }

            var model = entity.Adapt<EmailTemplateViewModel>();
            return View(model);
        }


        // POST /email/delete/4
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(LanguageViewModel model)
        {
            var entity = await emailService.GetEmailByIdAsync(model.Id);
            await emailService.DeleteEmailAsync(entity);
            await logService.DeleteManyLogsAsync(x => x.EntityID == entity.Id);

            TempData["Success"] = Warnings.SuccessfullyDeletedGeneric<Email>();

            return RedirectToAction("Index");
        }

        // GET /language/details/3
        public async Task<ActionResult> Details(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction(actionName: nameof(Index),
                    controllerName: "Home");
            }

            var result = await emailService.GetEmailByIdAsync(id);
            ViewData["detailId"] = result.Id;

            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
    }
}

Library.Web/Controllers/TabController.cs
using Library.Model.Models;
using Library.Service;
using Library.Web.Models;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;


namespace Library.Web.Controllers
{
    public class TabController : Controller
    {
        private readonly ITabService _tabService;

        public TabController(ITabService tabService)
        {
            _tabService = tabService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetTabMenu()
        {
            var catAll = await _tabService.GetAllTabsAsync();

            var model = catAll
                .Where(category => category.ParentId == 0)
                .Select(x => new TabViewModel
                {
                    Id = x.Id,
                    TabName = x.TabName,
                    ParentId = x.ParentId,
                    Child = x.Child.Adapt<List<TabViewModel>>()
                }).ToList();

            return PartialView("~/Views/Shared/Partial/GetTabMenu.cshtml", model);
        }
    }
}

Library.Web/Views/Shared/GetTabMenu.cshtml
@using Microsoft.AspNetCore.Html
@*@using xxx.Models*@
@model IEnumerable<TabViewModel>

@ShowMenu(Model.ToList(), new TabViewModel())(null)
@{
    Func<dynamic, IHtmlContent> ShowMenu(List<TabViewModel> cats, TabViewModel parent) =>
    @<ul>
        @foreach (var cat in cats)
                {
        <li>
            @cat.TabName
            @if (cat.Child.Count() > 0)
            {
                @ShowMenu(cat.Child, cat)(null)
            }
        </li>
         }
    </ul>;
}

Library.Web/Views/Shared/_Identity.cshtml
@using Library.Model.Models;
@using Library.Web.Models.Account;
@using Windows.Web.Http;
@using Library.Service;
@using Library.Web;
@using Library.Web.HelperMethods;

@inject IUserService userservice;


@{
    var cookie = Context.Request.Cookies["Token"];
    var userId = -1;

    if(cookie != null)
        userId = Convert.ToInt32(TokenHelper.TokenDecryption(cookie));

    var user = await userservice.GetUserByIdAsync(userId);

    //var testUserName = User?.Identity?.Name; => returns null
}


@if (cookie == null || cookie == "")
{
    <li class="navbar-nav flex-grow-1" style="margin-left:850px">
    <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    </li>
    <li class="navbar-nav flex-grow-1">
        <a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="register">
            <i class="bi bi-person-plus"></i> Register
        </a>
    </li>
}

else
{
    <li class="nav-item dropdown" style="margin-left:860px">
        <a class="nav-link text-dark dropdown-toggle" asp-controller = "account" asp-action = "logout" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-badge" href="Book/Index"></i> Hello @user.Email
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" asp-controller="account" asp-action="profile">Profile</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
    </li>
<li style="height:50px">
    <a class="btn btn-outline-danger btn-sm" asp-controller="Account" asp-action="Logout">
        <i class="bi bi-box-arrow-in-right"></i> Log Out
    </a>
</li>	
}			

Library.Web/Views/Shared/_Layout.cshtml
@using Library.Service;
@using Library.Web;
@using Library.Web.HelperMethods;

@inject IUserService userService;

@{
    var cookie = Context.Request.Cookies["Token"];
    var userId = -1;

    if (cookie != null)
        userId = Convert.ToInt32(TokenHelper.TokenDecryption(cookie));

    var isAdmin = await userService.IsInRole(userId, "Admin");
}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/LibraryManagementSystem.styles.css" asp-append-version="true" />

	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <script src="https://cdn.tiny.cloud/1/oo2v4hbe7s3kdjgfycjxazifss03z0de5ib174q2q5co6grm/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea#tiny',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | a11ycheck casechange blocks | bold italic backcolor | alignleft aligncenter alignright alignjustify |' +
                'bullist numlist checklist outdent indent | removeformat | code table help'
        })
    </script>

    <script>
        $(function () {
            $.ajax({
                url: "Tab/GetTabMenu",
            }).done(function (data) {
                $("#menu").html(data);
            });
        })
    </script>
</head>
<body>
	<header style="background-color:cadetblue; height:100px" src="~/logo/logo3.png">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibManagementSystem</a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (userId != -1 && isAdmin)
                        {
                            <li class ="nav-item dropdown">
							    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                                   data-toggle="dropdown" aria-haspopup="true" aria-expended="false">
                                <i class="bi bi-gear"></i> Management
                                </a>

                                @*Management Tabs*@

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Index"><i class="bi bi-person"></i>&nbsp;Accounts&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Book" asp-action="Index"><i class=" bi bi-book"></i>&nbsp;Books&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Email" asp-action="Index"><i class="bi bi-envelope"></i>&nbsp;Emails&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Author" asp-action="Index"><i class="bi bi-author"></i>&nbsp;Authors&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Language" asp-action="Index"><i class="bi bi-language"></i>&nbsp;Language&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Position" asp-action="Index"><i class="bi bi-language"></i>&nbsp;Positions&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Publisher" asp-action="Index"><i class="bi bi-language"></i>&nbsp;Publishers&nbsp;</a>
                                    <a class="dropdown-item" asp-controller="Storage" asp-action="Index"><i class="bi bi-language"></i>&nbsp;Storages&nbsp;</a>
                                    @*<a class="dropdown-item" asp-controller="Tab" asp-action="Index"><i class="bi bi-language"></i>&nbsp;Tabs&nbsp;</a>*@
                                </div>
                            </li>                   
                        }
                       
                        <partial name="_Identity.cshtml" />
                    
                    </ul>
                </div>               
            </div>
        </nav>
    
    </header>    
    <div class="container" style="height:800px">
        <main role="main" class="pb-3">
            <div class="container">
                <main role="main">
                    @if (TempData["Success"] != null)
                    {
                        <div class="alert alert-success" style="text-align:center">
                            @TempData["Success"]
                        </div>
                    }
                    @if (TempData["Error"] != null)
                    {
                        <div class="alert alert-danger" style="text-align:center">
                            @TempData["Error"]
                        </div>
                    }
                </main>
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="height:100px">
        <div>
            &copy; 2023 - LibraryManagementSystem - N.Varamashvili <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Library.Web/Views/Shared/_Pager.cshtml
@model PagerModel

<tr style="width: 100%">
	<td colspan="6" align="center">
		<div class="container">
			@if (Model.TotalPages > 0)
			{
				<ul class="pagination justify-content-center">

					@if (Model.CurrentPage > 1)
					{
						<li class="page-item">
							<a class="page-link" asp-controller="Account" asp-action="Index" asp-route-pg="1">First</a>
						</li>
						<li class="page-item">
							<a class="page-link" asp-controller="Account" asp-action="Index" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
						</li>
					}

					@for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
					{
						<li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
							<a class="page-link" asp-controller="Account" asp-action="Index" asp-route-pg="@pge"> @pge </a>
						</li>
					}

					@if (Model.CurrentPage < Model.TotalPages)
					{
						<li class="page-item">
							<a class="page-link" asp-controller="Account" asp-action="Index" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
						</li>
						<li class="page-item">
							<a class="page-link" asp-controller="Account" asp-action="Index" asp-route-pg="@(Model.EndPage)">Last</a>
						</li>
					}
				</ul>
			}
		</div>
	</td>
</tr>